# Generated by Django 6.0.7 on 2026-07-18 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('wedding', 'Wedding'), ('conference', 'Conference'), ('hackathon', 'Hackathon'), ('festival', 'Festival'), ('workshop', 'Workshop'), ('sports', 'Sports'), ('meetup', 'Meetup'), ('seminar', 'Seminar'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('published', 'Published'), ('live', 'Live'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('location', models.JSONField(default=dict)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('expected_attendees', models.PositiveIntegerField(default=0)),
                ('budget_target_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('source', models.CharField(choices=[('user', 'User'), ('template', 'Template')], default='user', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('av', 'AV & Tech'), ('marketing', 'Marketing'), ('talent', 'Talent'), ('sponsorship', 'Sponsorship'), ('staffing', 'Staffing'), ('printing', 'Printing'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('decoration', 'Decoration'), ('misc', 'Miscellaneous')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('planned_minor', models.BigIntegerField(default=0)),
                ('committed_minor', models.BigIntegerField(default=0)),
                ('actual_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('source', models.CharField(choices=[('user', 'User'), ('template', 'Template')], default='user', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='planning.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('at_risk', 'At Risk')], default='pending', max_length=20)),
                ('is_critical_path', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('user', 'User'), ('template', 'Template')], default='user', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='planning.event')),
            ],
            options={
                'ordering': ['order', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('likelihood', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('impact', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('mitigation', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('template', 'Template')], default='user', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('mitigated', 'Mitigated'), ('accepted', 'Accepted'), ('closed', 'Closed')], default='open', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='planning.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=20)),
                ('source', models.CharField(choices=[('user', 'User'), ('template', 'Template')], default='user', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.task')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planning.event')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='planning.milestone')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
    ]
