# Generated by Django 6.0.7 on 2026-07-18 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('wedding', 'Wedding'), ('conference', 'Conference'), ('hackathon', 'Hackathon'), ('festival', 'Festival'), ('workshop', 'Workshop'), ('sports', 'Sports'), ('meetup', 'Meetup'), ('seminar', 'Seminar'), ('other', 'Other')], max_length=20)),
                ('blueprint', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='linked_ref_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='linked_ref_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='budgetlineitem',
            name='category',
            field=models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('av', 'Av'), ('marketing', 'Marketing'), ('talent', 'Talent'), ('sponsorship', 'Sponsorship'), ('staffing', 'Staffing'), ('printing', 'Printing'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('decoration', 'Decoration'), ('misc', 'Misc')], max_length=30),
        ),
        migrations.AlterField(
            model_name='budgetlineitem',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('template', 'Template')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('template', 'Template')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('template', 'Template')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='risk',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('template', 'Template')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('template', 'Template')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='planning.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='planning.eventtemplate'),
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('layout', models.JSONField(default=dict)),
                ('assignments', models.JSONField(default=dict)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plan', to='planning.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
