# Generated by Django 6.0.7 on 2026-07-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_remove_budgetlineitem_linked_ref_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlineitem',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('template', 'Template'), ('ai', 'Ai')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('template', 'Template'), ('ai', 'Ai')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('template', 'Template'), ('ai', 'Ai')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='risk',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('template', 'Template'), ('ai', 'Ai')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('template', 'Template'), ('ai', 'Ai')], default='user', max_length=20),
        ),
    ]
