# Generated by Django 6.0.7 on 2026-07-21 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0008_alter_budgetlineitem_source_alter_event_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEventState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_status', models.CharField(blank=True, max_length=40)),
                ('requirements', models.JSONField(default=list)),
                ('vendors', models.JSONField(default=list)),
                ('guests', models.JSONField(default=list)),
                ('notes', models.JSONField(default=list)),
                ('timeline_meta', models.JSONField(default=dict)),
                ('snapshot', models.JSONField(default=dict)),
                ('organizer_id', models.UUIDField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_state', to='planning.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
