# Generated by Django 6.0.7 on 2026-07-21 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permissiongrant'),
        ('orchestration', '0002_agentmemory'),
        ('planning', '0008_alter_budgetlineitem_source_alter_event_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_text', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('intent', models.CharField(blank=True, max_length=40)),
                ('ai_state', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('clarifying', models.BooleanField(default=False)),
                ('missing_fields', models.JSONField(default=list)),
                ('plan', models.JSONField(default=dict)),
                ('explanation', models.JSONField(default=list)),
                ('pending_approvals', models.JSONField(default=list)),
                ('observability', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='planning.event')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_id', models.CharField(max_length=60)),
                ('skill', models.CharField(max_length=60)),
                ('outcome', models.CharField(max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('explanation', models.JSONField(default=list)),
                ('error', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='orchestration.agentrun')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_approvals', models.JSONField(default=list)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to='planning.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agentrun',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='orchestration.agentsession'),
        ),
        migrations.CreateModel(
            name='AgentTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=12)),
                ('content', models.TextField()),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='orchestration.agentrun')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='orchestration.agentsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['event', 'created_at'], name='orchestrati_event_i_c0d6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['session', 'created_at'], name='orchestrati_session_a6c6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status'], name='orchestrati_status_db6c02_idx'),
        ),
    ]
