import { AlertTriangle, Calendar, CalendarDays, CheckSquare, ChevronLeft, LayoutDashboard, LogOut, Menu, Sparkles, Store, Wallet } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Link, NavLink, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { Logo } from "../designed/app/components/Logo";

interface AppShellProps { children: ReactNode; eventId?: string; tone?: "light" | "dark"; title?: string; }
const planningLinks = [
  { label: "Timeline", suffix: "/planning/timeline", icon: CalendarDays }, { label: "Budget", suffix: "/planning/budget", icon: Wallet },
  { label: "Tasks", suffix: "/planning/tasks", icon: CheckSquare }, { label: "Calendar", suffix: "/planning/calendar", icon: Calendar }, { label: "Risks", suffix: "/planning/risks", icon: AlertTriangle },
];
function itemClass(active: boolean) { return "focus-ring flex w-full items-center gap-3 rounded-[10px] px-3 py-2 text-left text-[15px] transition " + (active ? "bg-white text-black" : "text-white/80 hover:bg-white/10 hover:text-white"); }

export function AppShell({ children, eventId, tone = "dark", title }: AppShellProps) {
  const [open, setOpen] = useState(false); const navigate = useNavigate(); const { user, signOut } = useAuth(); const dark = tone === "dark"; const close = () => setOpen(false);
  const sidebar = <aside className="flex h-full w-[300px] flex-col bg-black px-4 pb-8 pt-8 text-white"><Link to="/dashboard" onClick={close} className="focus-ring mx-2"><Logo textClassName="text-white" markSize={28} className="text-white" /></Link><nav className="mt-9 flex flex-1 flex-col gap-6 overflow-y-auto pr-1"><div className="flex flex-col gap-1"><NavLink to="/dashboard" onClick={close} className={({ isActive }) => itemClass(isActive)}><LayoutDashboard size={18}/>Dashboard</NavLink><NavLink to="/events" onClick={close} className={({ isActive }) => itemClass(isActive)}><CalendarDays size={18}/>Events</NavLink></div>{eventId && <><div className="flex flex-col gap-1"><NavLink to={`/events/${eventId}/copilot`} onClick={close} className={({ isActive }) => itemClass(isActive)}><Sparkles size={18}/>Copilot</NavLink><NavLink to={`/events/${eventId}/vendors`} onClick={close} className={({ isActive }) => itemClass(isActive)}><Store size={18}/>Vendors</NavLink></div><section><p className="mb-1 px-3 text-xs uppercase tracking-[.14em] text-white/40">Planning</p><div className="flex flex-col gap-1">{planningLinks.map(({ label, suffix, icon: Icon }) => <NavLink key={label} to={`/events/${eventId}${suffix}`} onClick={close} className={({ isActive }) => itemClass(isActive)}><Icon size={18}/>{label}</NavLink>)}</div></section></>}</nav><div className="mt-4 border-t border-white/10 pt-4"><button type="button" onClick={() => void signOut().then(() => navigate("/"))} className={itemClass(false)}><LogOut size={18}/>Sign out</button></div></aside>;
  return <div className={(dark ? "bg-black text-white" : "bg-[#F5F5F5] text-[#1A1A1A]") + " min-h-screen"}><div className="fixed inset-y-0 left-0 z-30 hidden lg:block">{sidebar}</div>{open && <div className="fixed inset-0 z-50 lg:hidden"><button type="button" aria-label="Close navigation" className="absolute inset-0 bg-black/60" onClick={close}/><div className="absolute inset-y-0 left-0">{sidebar}</div></div>}<main className="min-h-screen lg:pl-[300px]"><header className={(dark ? "border-white/10 bg-black/90" : "border-black/10 bg-[#F5F5F5]/90") + " sticky top-0 z-20 flex h-[72px] items-center gap-3 border-b px-4 backdrop-blur sm:px-8"}><button type="button" className={(dark ? "text-white" : "text-black") + " focus-ring rounded-full p-2 lg:hidden"} aria-label="Open navigation" onClick={() => setOpen(true)}><Menu size={21}/></button>{eventId && <Link to="/events" className={(dark ? "text-white/55" : "text-black/55") + " focus-ring hidden items-center gap-1 text-sm sm:flex"}><ChevronLeft size={16}/>Events</Link>}<div className="min-w-0 flex-1">{title && <p className="truncate text-[22px] font-editorial">{title}</p>}{eventId && !title && <p className={(dark ? "text-white/64" : "text-black/64") + " truncate text-sm"}>Event planning</p>}</div><span className={(dark ? "text-white/64" : "text-black/64") + " hidden max-w-32 truncate text-sm md:block"}>{user?.first_name || user?.email}</span></header><div className="mx-auto max-w-[1500px] p-4 sm:p-8">{children}</div></main></div>;
}
