import { useMutation } from "@tanstack/react-query";
import { Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { planningApi } from "../api/planning";
import type { BudgetLineItem, Event, Milestone, Risk, Task } from "../types";
import { Button, Input, Loading } from "./ui";

type Tab = "timeline" | "budget" | "tasks" | "calendar" | "risks";
type Props = { eventId: string; tab: Tab; event?: Event; milestones: Milestone[]; tasks: Task[]; risks: Risk[]; budget: BudgetLineItem[]; budgetSummary?: Record<string, number>; loading: boolean; refresh: (keys: string[]) => void; };
const tabs: Array<{ key: Tab; label: string }> = [{ key: "timeline", label: "Timeline" }, { key: "budget", label: "Budget" }, { key: "tasks", label: "Tasks" }, { key: "calendar", label: "Calendar" }, { key: "risks", label: "Risks" }];
const money = (value = 0, currency = "NPR") => new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 0 }).format(value / 100);
const date = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)) : "Unscheduled";
function ErrorText({ error }: { error: Error | null }) { return error ? <p role="alert" className="mt-3 text-sm text-red-300">{error.message}</p> : null; }

export function DesignedPlanningWorkspace(props: Props) {
  const { eventId, tab } = props;
  return <section className="overflow-hidden rounded-[28px] border border-white/15 bg-[#141414]"><div className="border-b border-white/10 p-5 sm:p-8"><p className="text-xs uppercase tracking-[.16em] text-white/40">Manual event planning</p><h1 className="font-editorial mt-2 text-4xl text-white">Keep the event on track.</h1><div className="mt-6 flex flex-wrap gap-2">{tabs.map((item) => <Link key={item.key} to={`/events/${eventId}/planning/${item.key}`} className={(tab === item.key ? "bg-white text-black" : "border border-white/15 text-white/64 hover:bg-white/10") + " rounded-full px-4 py-2 text-sm"}>{item.label}</Link>)}</div></div>{tab === "timeline" && <Timeline {...props}/>} {tab === "tasks" && <Tasks {...props}/>} {tab === "budget" && <Budget {...props}/>} {tab === "risks" && <Risks {...props}/>} {tab === "calendar" && <Calendar {...props}/>}</section>;
}

function Timeline({ eventId, event, milestones, loading, refresh }: Props) {
  const [title, setTitle] = useState(""); const [dueAt, setDueAt] = useState("");
  const add = useMutation({ mutationFn: () => planningApi.createMilestone(eventId, { title, due_at: dueAt ? new Date(dueAt).toISOString() : null, status: "pending" }, event?.revision), onSuccess: () => { setTitle(""); setDueAt(""); refresh(["milestones"]); } });
  const remove = useMutation({ mutationFn: (id: string) => planningApi.deleteMilestone(eventId, id), onSuccess: () => refresh(["milestones"]) });
  return <div className="p-5 sm:p-8"><form className="grid gap-3 sm:grid-cols-[1fr_220px_auto]" onSubmit={(e) => { e.preventDefault(); if (title.trim()) add.mutate(); }}><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Add a milestone"/><Input type="datetime-local" value={dueAt} onChange={(e) => setDueAt(e.target.value)}/><Button disabled={add.isPending}><Plus size={16}/>Add milestone</Button></form><ErrorText error={add.error}/>{loading ? <Loading/> : <div className="mt-6 divide-y divide-white/10">{milestones.map((item) => <article className="flex items-center justify-between gap-4 py-4" key={item.id}><div><p className="text-white">{item.title}</p><p className="mt-1 text-sm text-white/48">{date(item.due_at)} · {item.status.replace(/_/g, " ")}</p></div><button type="button" onClick={() => remove.mutate(item.id)} className="rounded-full p-2 text-white/45 hover:bg-white/10" aria-label={`Delete ${item.title}`}><Trash2 size={16}/></button></article>)}{!milestones.length && <p className="py-10 text-center text-sm text-white/48">Add the deadlines that define this event.</p>}</div>}</div>;
}

function Tasks({ eventId, event, tasks, loading, refresh }: Props) {
  const [title, setTitle] = useState(""); const add = useMutation({ mutationFn: () => planningApi.createTask(eventId, { title, status: "todo" }, event?.revision), onSuccess: () => { setTitle(""); refresh(["tasks"]); } }); const update = useMutation({ mutationFn: (task: Task) => planningApi.updateTask(eventId, task.id, { status: task.status === "done" ? "todo" : "done" }, event?.revision), onSuccess: () => refresh(["tasks"]) }); const remove = useMutation({ mutationFn: (id: string) => planningApi.deleteTask(eventId, id), onSuccess: () => refresh(["tasks"]) });
  return <div className="p-5 sm:p-8"><form className="flex gap-3" onSubmit={(e) => { e.preventDefault(); if (title.trim()) add.mutate(); }}><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Add a task"/><Button disabled={add.isPending}><Plus size={16}/>Add task</Button></form><ErrorText error={add.error}/>{loading ? <Loading/> : <div className="mt-6 divide-y divide-white/10">{tasks.map((task) => <article className="flex items-center gap-4 py-4" key={task.id}><input type="checkbox" className="size-4 accent-white" checked={task.status === "done"} onChange={() => update.mutate(task)} aria-label={`Mark ${task.title} complete`}/><div className="min-w-0 flex-1"><p className={task.status === "done" ? "text-white/40 line-through" : "text-white"}>{task.title}</p><p className="mt-1 text-sm text-white/48">{date(task.due_at)} · {task.status.replace(/_/g, " ")}</p></div><button type="button" onClick={() => remove.mutate(task.id)} className="rounded-full p-2 text-white/45 hover:bg-white/10" aria-label={`Delete ${task.title}`}><Trash2 size={16}/></button></article>)}{!tasks.length && <p className="py-10 text-center text-sm text-white/48">No tasks yet.</p>}</div>}</div>;
}

function Budget({ eventId, event, budget, budgetSummary, loading, refresh }: Props) {
  const [label, setLabel] = useState(""); const [amount, setAmount] = useState(""); const add = useMutation({ mutationFn: () => planningApi.replaceBudget(eventId, [...budget.map((item) => ({ category: item.category, label: item.label, planned_minor: item.planned_minor, committed_minor: item.committed_minor, actual_minor: item.actual_minor, currency: item.currency })), { category: "misc", label, planned_minor: Number(amount || 0), currency: event?.currency ?? "NPR" }], event?.revision), onSuccess: () => { setLabel(""); setAmount(""); refresh(["budget"]); } });
  return <div className="p-5 sm:p-8"><p className="text-sm text-white/56">Planned: {money(budgetSummary?.planned_minor, event?.currency)}</p><form className="mt-5 grid gap-3 sm:grid-cols-[1fr_220px_auto]" onSubmit={(e) => { e.preventDefault(); if (label.trim()) add.mutate(); }}><Input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Budget item"/><Input type="number" min="0" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="Minor units"/><Button disabled={add.isPending}><Plus size={16}/>Add item</Button></form><ErrorText error={add.error}/>{loading ? <Loading/> : <div className="mt-6 divide-y divide-white/10">{budget.map((item) => <article className="flex justify-between gap-4 py-4" key={item.id}><span className="text-white">{item.label || item.category}</span><span className="text-white/64">{money(item.planned_minor, item.currency)}</span></article>)}{!budget.length && <p className="py-10 text-center text-sm text-white/48">Track the costs you expect for this event.</p>}</div>}</div>;
}

function Risks({ eventId, event, risks, loading, refresh }: Props) {
  const [title, setTitle] = useState(""); const add = useMutation({ mutationFn: () => planningApi.createRisk(eventId, { title, likelihood: "medium", impact: "medium", mitigation: "" }, event?.revision), onSuccess: () => { setTitle(""); refresh(["risks"]); } }); const remove = useMutation({ mutationFn: (id: string) => planningApi.deleteRisk(eventId, id), onSuccess: () => refresh(["risks"]) });
  return <div className="p-5 sm:p-8"><form className="flex gap-3" onSubmit={(e) => { e.preventDefault(); if (title.trim()) add.mutate(); }}><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Add a risk"/><Button disabled={add.isPending}><Plus size={16}/>Add risk</Button></form><ErrorText error={add.error}/>{loading ? <Loading/> : <div className="mt-6 grid gap-4 md:grid-cols-2">{risks.map((risk) => <article className="rounded-[20px] border border-white/15 p-5" key={risk.id}><div className="flex items-start justify-between gap-4"><div><h2 className="text-white">{risk.title}</h2><p className="mt-2 text-sm text-white/48">{risk.likelihood} likelihood · {risk.impact} impact</p></div><button type="button" onClick={() => remove.mutate(risk.id)} className="rounded-full p-2 text-white/45 hover:bg-white/10" aria-label={`Delete ${risk.title}`}><Trash2 size={16}/></button></div><p className="mt-4 text-sm text-white/64">{risk.mitigation || "No mitigation recorded."}</p></article>)}{!risks.length && <p className="py-10 text-center text-sm text-white/48 md:col-span-2">No risks recorded yet.</p>}</div>}</div>;
}

function Calendar({ milestones, tasks }: Props) { const dated = [...milestones.map((item) => ({ title: item.title, due_at: item.due_at, type: "Milestone" })), ...tasks.map((item) => ({ title: item.title, due_at: item.due_at, type: "Task" }))].filter((item) => item.due_at).sort((a, b) => String(a.due_at).localeCompare(String(b.due_at))); return <div className="p-5 sm:p-8"><p className="text-sm text-white/56">All dated work, in one place.</p><div className="mt-6 divide-y divide-white/10">{dated.map((item, index) => <article className="flex justify-between gap-4 py-4" key={`${item.type}-${index}`}><span className="text-white">{item.title}</span><span className="text-sm text-white/48">{date(item.due_at)} · {item.type}</span></article>)}{!dated.length && <p className="py-10 text-center text-sm text-white/48">Add dates to milestones or tasks to fill the calendar.</p>}</div></div>; }
