# Generated by Django 5.2.4 on 2026-08-18 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_permissiongrant'),
        ('marketplace', '0002_vendor_external_ref_vendor_external_source_and_more'),
        ('planning', '0008_alter_budgetlineitem_source_alter_event_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('photography', 'Photography'), ('videography', 'Videography'), ('printing', 'Printing'), ('merchandise', 'Merchandise'), ('security', 'Security'), ('decoration', 'Decoration'), ('booth', 'Booth'), ('av', 'Av'), ('internet', 'Internet'), ('transport', 'Transport'), ('hotel', 'Hotel'), ('insurance', 'Insurance'), ('cleaning', 'Cleaning')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('scope', models.TextField(blank=True)),
                ('requirements', models.JSONField(default=list)),
                ('budget_ceiling_minor', models.BigIntegerField(default=0)),
                ('share_budget', models.BooleanField(default=False)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('respond_by', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('source', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requests', to='planning.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requests', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party_type', models.CharField(choices=[('vendor', 'Vendor'), ('talent', 'Talent'), ('sponsor', 'Sponsor')], default='vendor', max_length=20)),
                ('party_name', models.CharField(max_length=255)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('responded', 'Responded'), ('declined', 'Declined'), ('no_channel', 'No Channel'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('quote_minor', models.BigIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reply_contact_name', models.CharField(blank=True, max_length=120)),
                ('reply_contact_email', models.EmailField(blank=True, max_length=254)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach', to='marketplace.vendor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach', to='procurement.procurementrequest')),
            ],
            options={
                'ordering': ['party_name'],
            },
        ),
        migrations.AddIndex(
            model_name='procurementrequest',
            index=models.Index(fields=['event', 'status'], name='procurement_event_i_e7b42b_idx'),
        ),
        migrations.AddIndex(
            model_name='outreach',
            index=models.Index(fields=['request', 'status'], name='procurement_request_ba634a_idx'),
        ),
        migrations.AddConstraint(
            model_name='outreach',
            constraint=models.UniqueConstraint(fields=('request', 'vendor'), name='unique_outreach_vendor_per_request'),
        ),
    ]
