import { useQueries, useQuery } from "@tanstack/react-query";
import { ArrowRight, CalendarDays, Users } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { planningApi } from "../../../api/planning";
import type { Event, Milestone } from "../../../types";
import { AppShell } from "../components/AppShell";

function when(value?: string | null) { if (!value) return "Unscheduled"; const days = Math.ceil((new Date(value).getTime() - Date.now()) / 86_400_000); return days <= 0 ? (days === 0 ? "Today" : "Overdue") : `In ${days} day${days === 1 ? "" : "s"}`; }

export default function Dashboard() {
  const navigate = useNavigate(); const events = useQuery({ queryKey: ["events"], queryFn: planningApi.listEvents }); const rows = events.data ?? []; const milestoneQueries = useQueries({ queries: rows.map((event) => ({ queryKey: ["milestones", event.id], queryFn: () => planningApi.milestones(event.id) })) }); const active = rows.filter((event) => !["completed", "archived"].includes(event.status)); const expected = active.reduce((sum, event) => sum + event.expected_attendees, 0); const upcoming = milestoneQueries.flatMap((query, index) => (query.data ?? []).map((milestone) => ({ event: rows[index], milestone }))).filter(({ milestone }) => milestone.due_at && milestone.status !== "done").sort((a, b) => String(a.milestone.due_at).localeCompare(String(b.milestone.due_at))).slice(0, 6); const primary = active[0] ?? rows[0];
  const stats = [{ label: "Active events", value: String(active.length), icon: CalendarDays, detail: `${rows.length} total events` }, { label: "Expected attendees", value: new Intl.NumberFormat().format(expected), icon: Users, detail: "Across active events" }, { label: "Upcoming milestones", value: String(upcoming.length), icon: CalendarDays, detail: "Across active events" }];
  return <AppShell><div className="mx-auto max-w-[1400px] px-4 py-8 sm:px-8"><header className="max-w-3xl"><p className="text-xs uppercase tracking-[.18em] text-white/40">Event management</p><h1 className="font-editorial mt-3 text-5xl leading-[1.08] text-white sm:text-6xl">A clear view of your events and deadlines.</h1><p className="mt-4 text-lg text-white/64">Create events, assign work, and keep important dates visible.</p></header><section className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map((stat) => { const Icon = stat.icon; return <article key={stat.label} className="rounded-[28px] border border-white/15 bg-[#141414] p-6"><div className="flex items-center justify-between"><p className="text-sm text-white/55">{stat.label}</p><Icon className="size-5 text-white/40"/></div><p className="mt-5 font-editorial text-4xl text-white">{stat.value}</p><p className="mt-2 text-sm text-white/40">{stat.detail}</p></article>; })}</section><section className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><article className="rounded-[28px] border border-white/15 bg-[#141414] p-6 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.16em] text-white/40">Next up</p><h2 className="font-editorial mt-2 text-3xl">Upcoming milestones</h2></div>{primary && <button type="button" className="rounded-full border border-white/20 px-4 py-2 text-sm text-white/72 hover:bg-white/10" onClick={() => navigate(`/events/${primary.id}/planning/timeline`)}>Open timeline</button>}</div>{events.isLoading ? <p className="py-12 text-white/55">Loading event data…</p> : upcoming.length ? <div className="mt-5 divide-y divide-white/10">{upcoming.map(({ event, milestone }) => <MilestoneRow key={milestone.id} event={event} milestone={milestone} onOpen={() => navigate(`/events/${event.id}/planning/timeline`)}/>)}</div> : <p className="mt-6 rounded-[24px] border border-dashed border-white/15 p-8 text-center text-sm text-white/55">No dated milestones yet. Add the first event deadline to create your live runway.</p>}</article><aside className="rounded-[28px] border border-white/15 bg-[#141414] p-6 sm:p-8"><p className="text-xs uppercase tracking-[.16em] text-white/40">Move work forward</p><h2 className="font-editorial mt-2 text-3xl">Quick actions</h2><button type="button" className="group mt-6 flex w-full items-center justify-between rounded-full border border-white/15 bg-[#1A1A1A] px-5 py-3 text-left text-sm text-white/80 hover:bg-white/10" onClick={() => navigate("/events/new")}><span>Create event</span><ArrowRight className="size-4 text-white/40"/></button></aside></section></div></AppShell>;
}

function MilestoneRow({ event, milestone, onOpen }: { event: Event; milestone: Milestone; onOpen: () => void }) { return <button type="button" onClick={onOpen} className="flex w-full items-center justify-between gap-4 py-4 text-left hover:bg-white/[.03]"><span><b className="text-sm font-medium text-white">{milestone.title}</b><span className="mt-1 block text-sm text-white/48">{event.title} · {milestone.status.replace(/_/g, " ")}</span></span><span className="shrink-0 rounded-full border border-white/15 px-3 py-1 text-xs text-white/64">{when(milestone.due_at)}</span></button>; }
