import { ArrowRight, CalendarDays, CheckSquare, Wallet } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Logo } from "../components/Logo";
import heroImage from "../../imports/LandingPage/69ae82ef8326e6b21df4d71032b51e9939041794.png";

export default function LandingPage() {
  const navigate = useNavigate();
  const features = [{ icon: CalendarDays, title: "Plan the schedule", text: "Track milestones and dates in one shared timeline." }, { icon: CheckSquare, title: "Manage tasks", text: "Keep every owner and next step visible." }, { icon: Wallet, title: "Track the budget", text: "Record planned costs as the event takes shape." }];
  return <div className="min-h-screen bg-black text-white"><header className="absolute inset-x-0 top-0 z-10 flex items-center justify-between border-b border-white/15 bg-black/35 px-4 py-4 backdrop-blur sm:px-8"><Logo textClassName="text-white" markSize={26} className="text-white"/><div className="flex items-center gap-3"><button type="button" onClick={() => navigate("/login")} className="rounded-full px-5 py-2 text-sm text-white/80">Login</button><button type="button" onClick={() => navigate("/signup")} className="rounded-full bg-white px-5 py-2 text-sm text-black">Sign up</button></div></header><main><section className="relative isolate flex min-h-[700px] items-end overflow-hidden px-4 pb-20 pt-32 sm:px-8 sm:pb-28"><img src={heroImage} alt="People gathering at an event" className="absolute inset-0 -z-20 size-full object-cover opacity-50"/><div className="absolute inset-0 -z-10 bg-gradient-to-t from-black via-black/70 to-black/15"/><div className="mx-auto w-full max-w-6xl"><p className="text-xs uppercase tracking-[.2em] text-white/60">Event management, made simple</p><h1 className="mt-5 max-w-3xl font-['Georgia_Pro:Light',serif] text-[clamp(48px,8vw,94px)] leading-[.98]">Make every event<br/><i>easy to run.</i></h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/70">Eccillo gives your team a focused place to create events, plan the work, manage budgets, and stay on schedule.</p><button type="button" onClick={() => navigate("/signup")} className="mt-9 inline-flex items-center gap-2 rounded-full bg-white px-7 py-3 text-sm text-black">Start managing events <ArrowRight size={16}/></button></div></section><section className="mx-auto max-w-6xl px-4 py-24 sm:px-8"><p className="text-xs uppercase tracking-[.2em] text-white/45">The essentials</p><div className="mt-6 grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-[28px] border border-white/15 bg-[#141414] p-7"><Icon className="size-6 text-white/65"/><h2 className="mt-10 font-['Georgia_Pro:Light',serif] text-3xl">{title}</h2><p className="mt-3 leading-7 text-white/60">{text}</p></article>)}</div></section></main><footer className="border-t border-white/10 px-4 py-8 text-sm text-white/45 sm:px-8">© 2026 Eccillo</footer></div>;
}
