# Generated by Django 6.0.7 on 2026-07-21 18:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_permissiongrant'),
        ('planning', '0007_remove_budgetlineitem_linked_ref_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('photography', 'Photography'), ('videography', 'Videography'), ('printing', 'Printing'), ('merchandise', 'Merchandise'), ('security', 'Security'), ('decoration', 'Decoration'), ('booth', 'Booth'), ('av', 'Av'), ('internet', 'Internet'), ('transport', 'Transport'), ('hotel', 'Hotel'), ('insurance', 'Insurance'), ('cleaning', 'Cleaning')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('service_areas', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('response_time_mins', models.PositiveIntegerField(default=0)),
                ('price_from_minor', models.BigIntegerField(default=0)),
                ('price_to_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('portfolio_images', models.JSONField(default=list)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('photography', 'Photography'), ('videography', 'Videography'), ('printing', 'Printing'), ('merchandise', 'Merchandise'), ('security', 'Security'), ('decoration', 'Decoration'), ('booth', 'Booth'), ('av', 'Av'), ('internet', 'Internet'), ('transport', 'Transport'), ('hotel', 'Hotel'), ('insurance', 'Insurance'), ('cleaning', 'Cleaning')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pricing_model', models.CharField(choices=[('flat', 'Flat'), ('per_person', 'Per Person'), ('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('custom', 'Custom')], default='flat', max_length=20)),
                ('price_from_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='NPR', max_length=3)),
                ('capacity_min', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity_max', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField(blank=True)),
                ('verified_booking', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_reviews', to='planning.event')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='marketplace.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True)),
                ('event_type', models.CharField(blank=True, max_length=30)),
                ('caption', models.TextField(blank=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='marketplace.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventVendorShortlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('ai_suggested', 'AI suggested')], default='user', max_length=20)),
                ('copilot_action_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_shortlists', to='planning.event')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_shortlists', to='marketplace.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('tentative', 'Tentative'), ('confirmed', 'Confirmed'), ('released', 'Released')], default='tentative', max_length=20)),
                ('linked_ref_type', models.CharField(blank=True, max_length=80)),
                ('linked_ref_id', models.UUIDField(blank=True, null=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.servicelisting')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_holds', to='marketplace.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['category', 'verification_status'], name='marketplace_categor_d768ab_idx'),
        ),
        migrations.AddIndex(
            model_name='eventvendorshortlist',
            index=models.Index(fields=['event', 'created_at'], name='marketplace_event_i_4eb015_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventvendorshortlist',
            constraint=models.UniqueConstraint(fields=('event', 'vendor'), name='unique_event_vendor_shortlist'),
        ),
    ]
