# Generated by Django 6.0.7 on 2026-07-21 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vendor',
            name='external_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendorDiscoveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('radius_m', models.PositiveIntegerField(default=15000)),
                ('provider', models.CharField(default='osm', max_length=20)),
                ('found', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['location', 'category', 'created_at'], name='marketplace_locatio_568048_idx')],
            },
        ),
    ]
