# Generated by Django 6.0.7 on 2026-07-18 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.UUIDField()),
                ('capability', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('approve', 'Approve'), ('sign', 'Sign')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='accounts.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'resource_type', 'resource_id', 'capability'), name='unique_permission_grant')],
            },
        ),
    ]
